### ISSUE TITLE
Webcontainer does not run when "pnpm preview --host", but it works when "pnpm dev --host".

### ISSUE THREAD

**Issue by jakekwak** [sveltejs/learn.svelte.dev#213]
When "pnpm preview --host", I got this.

<img width="1031" alt="Screenshot 2023-02-14 at 10 14 39 PM" src="https://user-images.githubusercontent.com/15811943/218751443-7d3672de-c798-49ee-a458-666ede72742a.png">

but when "pnpm dev --host", it is working good at localhost.

**Comment by tomoam** [comment]
Responses from dev-servers and learn.svelte.dev invoked with the `vite dev` command will include COOP and COEP headers, but responses from preview-servers invoked with the `vite preview` command will not include COOP and COEP header.

This is probably because the `vite preview` command starts a static web server. That is, `src/hooks.server.js` is not executed, so the response does not contain COOP and COEP headers, hence this issue.

Perhaps a tweak to the Vite configuration will fix it.

**Comment by jakekwak** [comment]
I added console.log message at `hooks.server.js`.  Both is printed. (`preview` and `dev`).

**Comment by tomoam** [comment]
@jakekwak In my environment, I tried adding console.log to `hooks.server.js`, but it does not print with `pnpm build && pnpm preview`. Could you give me detailed steps to reproduce this?

**Comment by jakekwak** [comment]
@tomoam   I saw the console log message yesterday, but not. today.
