### ISSUE TITLE
iframe flashes white between exercises in dark mode

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/learn.svelte.dev#261]

**Comment by tomoam** [comment]
There seem to be two causes of the iframe blinking white.

The first is a refresh that occurs when iframe.src is changed. This can be fixed by #268.

And the second is because the `background-color` is not set in SvelteKit's default `error.html`. This can be seen by following these steps: 
1. go to https://learn.svelte.dev/tutorial/ssr
2. click `solve`
3. click `reset`

We can fix this by adding a `error.html` which supports dark mode to the `content/tutorial/common/src` directory, but it will always be shown even in tutorials which do not explain the fallback error.

**Comment by Rich-Harris** [comment]
I wonder if the default fallback error page in SvelteKit itself should account for dark mode...

**Comment by tomoam** [comment]
Yeah, few may want dark mode support of the default fallback error page, but there is no downside.

For reference, the Next.js error page seems to support dark mode.
https://github.com/vercel/next.js/blob/1467be886a94ac2e66a0442bd6bec1dc53da6608/packages/next/src/pages/_error.tsx#L108-L111

**Comment by tomoam** [comment]
@Rich-Harris 
It seems that the old default error page still appears due to Vercel's Build Cache.
In the Japanese translation site, it was fixed by doing `Redeploy` in Vercel.
