### ISSUE TITLE
WebContainers are in beta now for Safari

### ISSUE THREAD

**Issue by thedenoff** [sveltejs/learn.svelte.dev#306]
Recent macOS update (13.3) bumped Safari to 16.4 which on [WebContainers Browser Support page](https://webcontainers.io/guides/browser-support#safari) isn't described as lacking some features anymore but now as "in beta".

WebContainer's landing page demo now successfully runs on Safari with `webcontainer_any_ua` in LocalStorage being set to any non-empty value
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/13051154/229371249-ab208271-7c3f-46bc-9642-7c177d38c790.png">

I haven't though tested "learn"s code with removed user-agent matching codepath. Maybe there are some parts of WebContainers functionality which "learn" uses and which still don't work. If there are, maybe it would be smart to change check from user-agent to these specific function(s). At least we're getting close

**Comment by Rich-Harris** [comment]
Feature-detection rather than UA sniffing would be ideal, yeah, though the docs aren't quite clear on how to do the feature detection (the 'such as' makes me nervous):

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1162160/229374767-3bf63d98-e709-48e5-80b6-35ae3fbbfaa7.png">

I've opened a request for a) `boot()` to throw in unsupported environments and/or b) the ability to know ahead of time if the environment is supported: https://github.com/stackblitz/webcontainer-core/issues/1021

**Comment by thedenoff** [comment]
Great, thank you for opening that request! Should I close then this one and watch there or leave this as is for now?

**Comment by Rich-Harris** [comment]
Let's leave this open, as we'll still need to do some work on our end if/when they make any changes on theirs

**Comment by thedenoff** [comment]
For those who really wants to learn.svelte.dev in Safari even _before_ this resolves: 

- it's possible in macOS 13.3 (or if you got Safari 16.4 in some other way), 
- make Safari pretend it's (for example) Chrome (in Dev menu) 
- tick "Disable Cross-Origin Restrictions" (in Dev menu too) 

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/13051154/229379915-417bca13-4d40-418c-b03c-29516a2d4b5e.png">

**Comment by thedenoff** [comment]
WebContainers team choose now to enable demo on their landing page for Safari by default. Here's [the check they used](https://github.com/stackblitz/webcontainer-docs/commit/369dd58b2749b085ed7642f22108a9bcbcd68fc4) in code. Maybe it's be good enough for learn too?

**Comment by tomoam** [comment]
According to this document, older Safari does not support `Atomics.waitAsync` and therefore cannot run Webcontainer.
https://webcontainers.io/guides/browser-support#safari

According to caniuse.com, I see that Safari has supported `Atomics.waitAsync` since 16.4, so this could be used to check for Webcontainer support, as a temporary workaround.
https://caniuse.com/mdn-javascript_builtins_atomics_waitasync.

**Comment by tomoam** [comment]
I have tried learn.svelte.dev on iPhone XS MAX and iPhone 13 Pro and it crashes. (On iPad Air (4th gen), it crashes rarely, but shows 'OUT OF MEMORY').

So again, I read the code in the docs of webcontainers.io and found that for mobile Safari, it is hidden by CSS.

https://github.com/stackblitz/webcontainer-docs/blob/369dd58b2749b085ed7642f22108a9bcbcd68fc4/docs/.vitepress/theme/components/Examples/WCEmbed/WCEmbed.vue#L133-L140

Stackblitz shows the following for mobile Safari:

<img width="408" alt="image" src="https://github.com/sveltejs/learn.svelte.dev/assets/29677552/a749c426-6536-4851-9c97-005bafcb62c5">

...then if you click the `Run this project` button on the iPhone XS MAX and iPhone 13 Pro, it crashes.

So I will improve the check logic to make it unavailable for Safari on iOS.
