### ISSUE TITLE
Examples in tutorial has unfriendly names

### ISSUE THREAD

**Issue by vhtmui** [sveltejs/learn.svelte.dev#650]
Such as `Part 2/Context API/setContext and getContext`, it has several `canvas` in defferent parts, and they are totally different things, It's really confusing for a novice like me.

Same thing happened in
*  `Part 2/Component composition/Slot props` , the word `item` appears in defferent and unrelated block.
*  `flipped` in `Part 2/Classes and styles/Shorthand class directive`.
*   and so on
 
In addition, `getContext` in `Part 2/Context API/setContext and getContext`, the name `getContext` is conflict with the method of canvas; 
and many places use the shorthand syntax. 
I don't know if this tutorial is for older birds, but all these things above I think are not friendly to beginners, because i'm not familiar to all those elements, api, attributes name of web standard and svelte.

**Comment by dummdidumm** [comment]
Could you clarify those points?

> Such as Part 2/Context API/setContext and getContext, it has several canvas in defferent parts, and they are totally different thing

There's a `canvas` variable, and there's the `Canvas` component which wraps a canvas element. There's no other names. What about this is confusing to you?

> In addition, getContext in Part 2/Context API/setContext and getContext, the name getContext is conflict with the method of canvas

This is indeed unfortunate but unavoidable. It just so happens that the DOM API chose the same name here. Maybe we should not use a canvas example here to not run into this situation; not sure.

> Part 2/Component composition/Slot props , the word item appears in defferent and unrelated block.

What do you mean by that exactly? `item` always relates to the same thing in all occurences. If this is about the `let:` syntax - yes, that is indeed a confusing aspect of the Slot Syntax in general, which is why in Svelte 5 you'll have Snippets which should make this more straightforward.

> flipped in Part 2/Classes and styles/Shorthand class directive.

The whole point of the tutorial is that there's a shorthand you can use if the class you apply and the variable you use to determine whether to apply it or not are the same.

**Comment by vhtmui** [comment]
Thanks for your answer  @dummdidumm , and im sorry as I got more familiar with it, some no longer confused me, but the one below is  still a bit confused i think:

* In `Part 2/Context API/setContext and getContext`, it would be better to change the context key name of 'canvas' to any other, this makes me think what does the key name 'canvas' have to do with the variable name 'canvas'. though there is an explanation on the left, but I've got the illusion after first looking at the code.

Of course, this is not a serious problem now.
